# numpy array의 생김새

In [2]:
import numpy
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])

[ 2  3  5  7 11 13 17 19 23 29 31]


In [13]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
type(array1)

numpy.ndarray

In [14]:
# array1에 몇개의 요소가 들어있는지 확인
array1.shape # numpy array의 모양

(11,)

In [16]:
# 2차원 array
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [18]:
type(array2)

numpy.ndarray

In [19]:
array2.shape

(3, 4)

In [20]:
array1.size

11

In [21]:
array2.size

12

# numpy array를 만드는 다양한 방법

In [22]:
# 파이썬 리스트를 통해 생성

array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


In [4]:
# 균일한 값으로 생성

array1 = numpy.full(6, 7)

print(array1)

[7 7 7 7 7 7]


In [5]:
# 모든 값이 0인 numpy array 생성

array1 = numpy.full(6, 0)
array2 = numpy.zeros(6, dtype=int)

print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [6]:
# 모든 값이 1인 numpy array 생성

array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype=int)

print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


In [7]:
# 랜덤한 값들로 생성

array1 = numpy.random.random(6)
array2 = numpy.random.random(6)

print(array1)
print()
print(array2)

[0.0356147  0.98979833 0.96732746 0.48283468 0.29114677 0.41808858]

[0.59404514 0.9351286  0.65008924 0.97707489 0.58827393 0.85097404]


In [8]:
# 연속된 값들이 담긴 numpy array 생성
# 파라미터 1개
# arange(m)을 하면 0부터 m-1까지의 값들이 담긴 numpy array가 리턴됩니다.

array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [9]:
# 파라미터 2개
# arange(n, m)을 하면 n부터 m-1까지의 값들이 담긴 numpy array가 리턴됩니다.

array1 = numpy.arange(2, 7)
print(array1)

[2 3 4 5 6]


In [10]:
# 파라미터 3개
# arange(n, m, s)를 하면 n부터 m-1까지의 값들 중 간격이 s인 값들이 담긴 numpy array가 리턴됩니다.

array1 = numpy.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]


# 모듈 별명 지어주기

In [11]:
import numpy as np
import matplotlib.pyplot as plt

array1 = np.full(6, 0)
array2 = np.zeros(6)
array3 = np.full(6, 6)
array4 = np.ones(9)
array5 = np.random.random(6)
array6 = np.random.random(10)

In [12]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
array1[0]
array1[2]
array1[-1]
array1[-2]
array1[[1, 3, 4]]

array([ 3,  7, 11])