In [1]:
import numpy as np

In [2]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [3]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
array1 = array1 * 2

In [11]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [12]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
array1 + array2

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [15]:
array1 * array2

array([  0,  22,  48,  78, 112, 150, 192, 238, 288, 342])

In [16]:
array1 / array2

array([0.        , 0.18181818, 0.33333333, 0.46153846, 0.57142857,
       0.66666667, 0.75      , 0.82352941, 0.88888889, 0.94736842])