# 각종 numpy 배열 생성방법

In [4]:
import numpy
array1 = numpy.array([2,3,5,7,11,13,17,19,23,29,31])
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


In [5]:
array1 = numpy.full(6, 7)

print(array1)

[7 7 7 7 7 7]


In [6]:
array1 = numpy.full(6, 0)
array2 = numpy.zeros(6, dtype=int)

print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [7]:
array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype=int)

print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


In [8]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)

print(array1)
print()
print(array2)

[0.0700052  0.18780593 0.13503544 0.69539763 0.10643662 0.21974033]

[0.11836322 0.28493339 0.81448677 0.49196689 0.35880605 0.73318308]


In [9]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [10]:
array1 = numpy.arange(2, 7)
print(array1)

[2 3 4 5 6]


In [11]:
array1 = numpy.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]


In [3]:
import numpy as np
import matplotlib.pyplot as plt

array1 = np.full(6, 0)
array2 = np.zeros(6)
array3 = np.full(6, 6)
array4 = np.ones(9)
array5 = np.random.random(6)
array6 = np.random.random(10)

In [5]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
array1[0]
array1[2]
array1[-1]
array1[-2]
array1[[1, 3, 4]]

array([ 3, 11, 13])